### ISSUE TITLE
Linux terminal

### ISSUE THREAD

**Issue by piranna** [hzeller/timg#10]
Maybe it would be possible to add full color by defining a correct `$TERM`. Regarding the UPPER_BLOCK character, probably it would be possible by using the CJKTTY patch, but I've not been able to enable it... :-/

**Comment by jdebp** [comment]
The inability of the Linux kernel's built-in terminal emulator to properly display 256×256×256 RGB "true colour" is not a deficiency in this program; nor is it fixed by adjusting terminal types.  Linux's built-in terminal emulator reduces 256×256×256 RGB to IBM PC Colour Graphics Array style 7-bit RGB, and the developers consider full colour support [a large amount of code](https://github.com/torvalds/linux/commit/cec5b2a97a11ade56a701e83044d0a2a984c67b4) to be putting into the kernel.

For this sort of thing, I recommend using one of the _user-space_ framebuffer terminal emulators that are available.  Some of them support 256×256×256 RGB are are quite happy with Unicode block graphic and box drawing characters.  See [this answer](http://unix.stackexchange.com/a/177209/5132) and [this answer](http://unix.stackexchange.com/a/303767/5132) on Stack Exchange for more on this.

**Comment by piranna** [comment]
I don't think is so much code, but kernel developers are too much picky to add more features to the Linux console. Anyway, maybe it would be made as a patch, isn't it?

**Comment by hzeller** [comment]
So, there is not much we can do in _this_ repository though :) So closing this for now.
