### ISSUE TITLE
Wrong aspect ratio with kitty

### ISSUE THREAD

**Issue by SolitudeSF** [hzeller/timg#44]
![image](https://user-images.githubusercontent.com/10168645/110213299-119c6600-7ea8-11eb-9b06-3edd1c6b262e.png)

**Comment by hzeller** [comment]
This is plausible, there was some font stretch correction applied that only made sense for the block-based fonts.
Can you try again ?

**Comment by hzeller** [comment]
Re-opened until confirmed working.

**Comment by SolitudeSF** [comment]
works

**Comment by SolitudeSF** [comment]
nvm, still wrong, probably because it aligns at cell edge?

**Comment by hzeller** [comment]
Yes, it might slightly squash things due to cell edge boundary and be off by that. Which probably would mean it could be off by 1-3% on a typical terminal. Hoping that it would not be _that_ noticeable.

I did that partially for future proofing as I plan to do differential updates for changes on the cell level, but maybe this needs to be revisited if it is super noticeable ?

**Comment by SolitudeSF** [comment]
it is super notable with any angled near-straight line

**Comment by hzeller** [comment]
Disabled this cell alignment now for pixel exact displays. Can you try again from head ?

**Comment by SolitudeSF** [comment]
all good now
