### ISSUE TITLE
License at https://snapcraft.io/timg shows as Proprietary, not GPL

### ISSUE THREAD

**Issue by MestreLion** [hzeller/timg#54]
Which one is correct? Is that an official snap?

**Comment by hzeller** [comment]
timg is, and always has been, [GPL2 licensed](https://github.com/hzeller/timg/blob/main/LICENSE).

I don't know anything about that snap package you mention. Please contact the maintainer of the package to fix the license they mention.

**Comment by MestreLion** [comment]
> I don't know anything about that snap package you mention. 

That is the package suggested by Ubuntu 18.04 when I tried to see if I already had `timg` installed:

```terminal
17:46:33 rodrigo@desktop ~ $ timg

Command 'timg' not found, but can be installed with:

sudo snap install timg

17:46:35 rodrigo@desktop ~ 127 $ snap info timg
name:      timg
summary:   A terminal image viewer
publisher: Simos Xenitellis (simosx)
store-url: https://snapcraft.io/timg
license:   Proprietary
description: |
  A viewer that uses 24-Bit color capabilities and unicode character blocks to display images in the
  terminal.
snap-id: ZN8M21m9vKYlPNnePQKhIkqXGXaCmec6
channels:
  latest/stable:    20170226 2017-05-17 (6) 11MB -
  latest/candidate: ↑                            
  latest/beta:      20170226 2017-05-17 (6) 11MB -
  latest/edge:      20170226 2017-05-17 (6) 11MB -
17:46:45 rodrigo@desktop ~ $ 
```

> Please contact the maintainer of the package to fix the license they mention.

_Me_? I'm not even a `timg` user! (yet) I just discovered this project, tried to see if it had any `apt` or `snap` available, and stumbled on that weird package. I'm just bringing this to your attention so you guys can ... well, do whatever authors do when they find someone published their GPL'd software as Proprietary in a highly visible platform such as snapcraft that's suggested by default by an LTS release of one of the most used distros :)

**Comment by hzeller** [comment]
@simos seems to be the github handle of the package maintainer.
Simos, can you fix the package to contain the proper license ?

**Comment by simos** [comment]
Here is the Github issue for packaging `timg` as a snap package, #12 and does go back to 2017.
I posted that issue after I wrote this post on snap packages, https://blog.simos.info/how-to-create-a-snap-for-timg-with-snapcraft-on-ubuntu/

Many things have changed for snap packaging since then. For example, the license can actually be set properly now. Also, there is a free build service to build automatically a snap package for you, and that service has hooks to github. And can autobuild for six architectures.

I almost finished the fresh snap packaging of timg. It needs a bit more extra work (fixing some libraries), and here is the latest version, https://github.com/simos/timg-snap/tree/master

**Comment by hzeller** [comment]
Cool, thanks @simos !
Also, this is a nice in-depth blog post, very nice.

We should probably add a line in the [Install pre-built package](https://github.com/hzeller/timg#install-pre-built-package) section in the README.

**Comment by hzeller** [comment]
FYI, if you had to do anything special to make cmake work on Ubuntu 18 @simos - good news: @MestreLion just fixed the CMake file to be accepted by the older cmake installed on that LTS version in pull request #55 (issue #53 ).

**Comment by simos** [comment]
Okay, I completed the snap package task and it is ready for testing. 
The package is available to the following architectures:
1. amd64, OK (tested by me)
2. i386, untested
3. armhf, untested
4. ppc64el, untested
5. s390x, untested
6. arm64, generated but was not released due to some review requirements. Cannot test yet.

In order to test on any of that above architectures, install the `snapd` package (Snap package support) and then run

```
sudo snap install timg --channel=edge
```

Note that I have not released yet this build and it can only by used when you specify the _edge_ channel.

**Comment by simos** [comment]
> FYI, if you had to do anything special to make cmake work on Ubuntu 18 @simos - good news: @MestreLion just fixed the CMake file to be accepted by the older cmake installed on that LTS version in pull request #55 (issue #53 ).

Thanks for this. I switched the snap package to get generated over the Ubuntu 18.04 Core image (instead of the Ubuntu 20.04 Core image). 

The package uses the `strict` confinement, which means that it can read image files and videos from the $HOME/* directory only. It is possible to expand this with some extra steps; for now we just keep this in mind to inform the testers. If, for example, you try to open an image from `/tmp/`, it will fail due to access violation.

The package weighs now around 87MB, due to the dependenices (video, GPU). Someone more experienced in snap packages should probably be able to reduce the size. 

There is a feature at https://snapcraft.io/snaps to add additional people are _collaborators_ in the management of the snap package. If you are interested in this, create a command and tell me the username so that I can add you.

Therefore, at this stage we are interested in testing the _edge_ snap package, and release those versions that are tested. There is a chance that in some architectures the snap package does not work because it uses OpenGL libraries. We would like to know and make sure we do not release for an architecture that does not work.

**Comment by hzeller** [comment]
I suspect that OpenGL only really is needed if Graphicsmagic++ or libavi needs to open a file that requires that. These libraries are kitchen-sinks of image format access and pull in a lot of dependencies that are probably not needed most of the time.

**Comment by simos** [comment]
> I suspect that OpenGL only really is needed if Graphicsmagic++ or libavi needs to open a file that requires that. These libraries are kitchen-sinks of image format access and pull in a lot of dependencies that are probably not needed most of the time.

I had a second look at the issue and could not find any low-hanging fruits to reduce the package size. I think that since it works, it should be OK. The importance is the availability of the application and the size is only secondary. 

I have set all architectures live for the `timg` snap package. I have tested the `amd64` architecture on both an Ubuntu desktop and on a VPS running Ubuntu. 

I created a PR for README.md that has instructions on how to install the snap package. 

The license issue has been fixed, now it's GPL 2.0.

There are about 50 users of [the `timg` snap package](https://snapcraft.io/timg). That's users that have been using the 2017 version of `timg`. We can see how it builds from there. 

If you would like to co-manage or have a look at the snap package development page, [create a Launchpad account](https://launchpad.net/) and send me the username. This would be also useful if you want to add screenshots or an app icon on the Snap Store. 

At the moment, the snap package is using the latest (git) version because of the CMake fix that can build on the Ubuntu 18.04 base. Currently, for snap packages, the default runtime is 18.04. This means that users would not have to download the 20.04 runtime.

**Comment by hzeller** [comment]
Thanks for updating the package!

Yeah, I think size these days is not too big of a deal anymore when every computer comes with at least a terabyte of space...

If it helps, I can tag a 1.4.1 version, just so that we have the latest cmake changes in.

**Comment by hzeller** [comment]
Since the package is now updated (thanks @simos !), the license is shown correctly in https://snapcraft.io/timg so this can be closed.

**Comment by simos** [comment]
> If it helps, I can tag a 1.4.1 version, just so that we have the latest cmake changes in.

That would be great.

**Comment by hzeller** [comment]
Alright, tagged https://github.com/hzeller/timg/releases/tag/v1.4.1

**Comment by simos** [comment]
So, I am doing now the following,

1. Went to https://github.com/simos/timg-snap/blob/main/snap/snapcraft.yaml and edited the file from the Web to set the tag line to `source-tag: v1.4.1`.
2. This change triggered automatically the build servers and they started creating snap packages for those six architectures. I just sit and observe at https://snapcraft.io/timg/builds (you can view too, if you create a free account and I add you as a _collaborator_).
3. Once all packages get built, I go to https://snapcraft.io/timg/releases and click on **Promote to: latest/stable** and click on **Save**.

and that's it. We got packages for timg 1.4.1. It's now live.

**Comment by hzeller** [comment]
Is the 'strict' confinement there to test how this option work ? I don't think it makes sense in the general context, as you usually _do_ want to look at images such as icons and whatnot on your system. So it is too restrictive without any benefits.

**Comment by simos** [comment]
The `strict` confinement is the default confinement and allows you to publish a snap without requiring permissions. 

The next level is to still keep the `strict` confinement but ask (at the Snap forum) to enable the `removable-media` interface. By doing so, `timg` will be able to access both the _home_ folder and any removable media disks that have been mounted to `/media/`. 

The last level is to switch to the `classic` confinement, which would make `timg` access any part of the system. This would require to prepare the request according to the instructions at https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460 A quick read makes me think that a request here is likely to fail.

Considering that I have not managed to make you collaborator in the snap package development, I should be the one requesting something from the above.

FYI, https://blog.simos.info/timg-a-text-mode-image-viewer-and-video-player/
