### ISSUE TITLE
PKGBUILD in AUR

### ISSUE THREAD

**Issue by grigorii-horos** [hzeller/timg#8]
You can add PKGBUILD in AUR?

**Comment by horosgrisa** [comment]
https://aur.archlinux.org/packages/timg/

**Comment by hzeller** [comment]
Mmh, I have trouble parsing this - do you mean I should add the PKGBUILD file, that is also managed in aur, in this project ? Or simply add a Readme that points to https://aur.archlinux.org/packages/timg/ ?

Can you send me a pull request that adds it ? Directory should probably something like dist-scripts/arch, so that there is more for debian etc.
So `dist-scripts/arch/PKGBUILD` or  `dist-scripts/arch/README` depending on what your intention is.

**Comment by horosgrisa** [comment]
@hzeller When I discovered that your package isn't present in AUR I opened this issue, but after an hour I decided to add your package in AUR.

**Comment by horosgrisa** [comment]
@hzeller PKGBUILD in `dist-scripts/arch/PKGBUILD` have no sense, because this PKGBUILD should be changed after each commit.

**Comment by horosgrisa** [comment]
@hzeller do you have account in AUR?

**Comment by hzeller** [comment]
I don't have an account on AUR.

BTW, I have now made a new release [v0.9.5](https://github.com/hzeller/timg/releases/tag/v0.9.5) that represents current head, so that you don't have to do the 0.9.1beta tar.

**Comment by hzeller** [comment]
Looks like https://aur.archlinux.org/packages/timg/ has been up for a while and tracks latest version. Closing this bug now.
