### ISSUE TITLE
Stucks on a "iOS optimized PNG" file

### ISSUE THREAD

**Issue by Tigerfyj** [hzeller/timg#85]
timg stucks on a png file in my linux terminal. The file came from a macbook.

- "display" can open the image correctly.
- "mediainfo" returns normal information.
- "ffprode" returns an error message: "inflate returned error -3".
- "viu" returns an error message: "CgBI chunk appeared before IHDR chunk"

After some searches, I found a similar question: https://stackoverflow.com/questions/21359540/strange-png-errors-bad-length-for-ihdr-chunk
It references to this document finally: https://iphonedev.wiki/index.php/CgBI_file_format

```
$ timg --version
timg 1.4.4+ (Debian package 1.4.4-1+build1) <https://timg.sh/>
Copyright (c) 2016..2021 Henner Zeller. This program is free software; license GPL 2.0.

Image decoding GraphicsMagick 1.3.38 (2022-03-26)
Openslide 3.4.1
Video decoding libav 59.16.100
```

**Comment by hzeller** [comment]
The iphonedev.wiki explains the reason why it does not work:

_These modifications cause the generated images to be invalid as per the current version of the PNG standard._

Since `timg` is using GraphicsMagick (which then in turn probably will use libpng), these features will need to be added in these projects.

You can attempt to see if the video subsystem can deal with the file. Call `timg -V <yourimage>`.

Until then, I'd probably suggest to only use images that follow the standard and stay away from proprietary image extensions.

Anyway, nothing `timg` can do, this is something the underlying libraries need to support.

**Comment by Tigerfyj** [comment]
Thanks for your reply, Henner. I would expect timg can return an error message rather than stucking.
In my case, I run `timg --grid=4 *.png`. The list stopped at this file. The command didn't finish. It would be nice to either skip the file or display a placeholder.

**Comment by hzeller** [comment]
do you have an image like that that you can share in this bug ?

**Comment by Tigerfyj** [comment]
Uploaded. Thanks for your effort!
![apple-only](https://user-images.githubusercontent.com/3694642/189062388-2f93a2a4-514d-4ac7-b0c4-cb717eb8c3e7.png)

**Comment by hzeller** [comment]
Alright, looks like the STB image loading library is actually able to deal with these images. By default, it was configured off, but I now changed it so that it is default on as fallback.

That way, not only will `timg` not hang on the image, but actually be able to display it!

**Comment by Tigerfyj** [comment]
Thanks for your help, Henner! I built a new binary. It works perfect!
