### ISSUE TITLE
How to disable this error(warning)?

### ISSUE THREAD

**Issue by bropines** [hzeller/timg#86]
![IMG_20220918_102927](https://user-images.githubusercontent.com/57861007/190887311-3779e5be-1aae-4aa7-a565-0b62d1191730.jpg)
This annoying warning bothers me very much. Is there any parameter hiding warnings?
Termux, v 1.4.4
Warning "Terminal does not support pixel size query, but graphics protocol requested.
Can't show animations or have columns in grid."

**Comment by hzeller** [comment]
Maybe I should only actually trigger the warning in case column mode or animation is requested in the first place, I'll have a look into that.

This warning is triggered because the terminal, on request with `TIOCGWINSZ`, does not fill in the fields `ws_xpixel` and `ws_ypixel`, which would probably good to file as issue to the termux developers.

**Comment by hzeller** [comment]
Alright, now the warning only will show up if there was an animation that could only display its first frame or if multi-column mode was requested.

The real solution though is for you to file a ticket with termux to implement the `TIOCGWINSZ` information.

**Comment by hzeller** [comment]
Also, if you file issues with termux, ask them to implement the ` \033[>q` CSI query, that way we could detect termux and automatically switch to `-pi` mode.

**Comment by bropines** [comment]
> Also, if you file issues with termux, ask them to implement the ` \033[>q` CSI query, that way we could detect termux and automatically switch to `-pi` mode.

I think I'll open an issue tomorrow and leave links to this discussion.
