### ISSUE TITLE
Option to show all images at once with `--grid` and `-w`

### ISSUE THREAD

**Issue by Chaz6** [hzeller/timg#87]
When using the grid option in combination with the wait time option to make a slide show, it would be useful to have have an option to show all the images in the grid at once. For example, `timg -w5 --grid=2x1 image1.jpg image2.jpg image3.jpg image4.jpg` would show `image1.jpg` and `image2.jpg`, then wait 5 seconds, then show `image3.jpg` and `image4.jpg` in a 2 by 1 grid.

**Comment by hzeller** [comment]
Ah, you mean essentially have `-w` apply per row not per image.
`-w` comes from a time when there was no grid display in `timg` yet, so indeed it makes sense to reconsider.

**Comment by Chaz6** [comment]
Yes please, you got it!

**Comment by hzeller** [comment]
Added a new option `-wr` that allows to set the wait time per row. It can be combined with `-w` so that you can have a wait per image and then an additional wait time per row.

Will be in the next release. Here is [an AppImage](https://github.com/hzeller/timg/suites/14367342872/artifacts/809340673) if you want to try it out.
